# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0003_auto_20170620_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='image',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='resource_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fingerprintedlocation',
            name='floor_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locator.PointOfInterest'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
