# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0004_auto_20170621_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintedlocation',
            name='point_of_interest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locator.PointOfInterest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fingerprintedlocation',
            name='floor_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locator.FloorPlan'),
        ),
    ]
