# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0005_auto_20170622_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintedlocation',
            name='is_poi',
            field=models.BooleanField(default=False),
        ),
    ]
