# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0006_fingerprintedlocation_is_poi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprintedlocation',
            name='point_of_interest',
        ),
        migrations.AddField(
            model_name='fingerprintedlocation',
            name='related_poi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locator.PointOfInterest'),
        ),
    ]
