# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0007_auto_20170622_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='fingerprinted_loc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='locator.FingerPrintedLocation'),
            preserve_default=False,
        ),
    ]
