# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0008_pointofinterest_fingerprinted_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='fingerprinted_loc',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='x_coord',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='y_coord',
        ),
    ]
