# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0012_auto_20170704_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'pointOfInterest/'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locator.Creator'),
        ),
    ]
