# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0013_auto_20170713_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='creator',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
